export default {
	TESTNET: true,
	VOTING_TOKEN_SYMBOL: "GBYTE",
	VOTING_TOKEN_DECIMALS: 9,
	PROVIDER_DICTIONARY: {
		"F4KHJUCLJKY4JV7M5F754LAJX4EB7M4N": "Tony Churyumoff",
		"OPNUXBRSSQQGHKQNEPD2GLWQYEUY5XLD": "Tony Churyumoff"
	}
}
